print('Quasar')
print('the most basic programming language')
print('if you have a very limited keyboard')
print('chardelyce edwards 2022')
print('https://github.com/chardelyce/Quasar')
print('--------------------------------')